name: Publish

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'  # release candidate tags
      - 'v[0-9]+.[0-9]+.[0-9]+a[0-9]+'  # alpha tags
      - 'v[0-9]+.[0-9]+.[0-9]+b[0-9]+'  # beta tags

jobs:
  Publish:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Detect pre-release tag
        run: |
          if [[ ${{ env.tag }} =~ ^v[0-9]+.[0-9]+.[0-9]+rc[0-9]+$ ||
                ${{ env.tag }} =~ ^v[0-9]+.[0-9]+.[0-9]+a[0-9]+$ ||
                ${{ env.tag }} =~ ^v[0-9]+.[0-9]+.[0-9]+b[0-9]+$
          ]]; then
              echo "pre_release=true" >> $GITHUB_ENV
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.2.2

      - name: Install dependencies
        run: |
          poetry update
          poetry run pip install --upgrade setuptools

      - name: Update version strings
        run: |
          poetry version ${{ env.tag }}
          sed -i "s/0.0.0/${{ env.tag }}/g" seabird_sbe/__init__.py

      - name: Build
        run: poetry build

      - name: Publish
        if: |
          ${{ !env.ACT }}  # skip during local actions testing
          && ${{ !env.pre_release }}  # skip pre-release versions
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish
